name: Article
on: [push, pull_request]
jobs:
    build_article:
        name: Build a test article
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - uses: actions/checkout@v2
            - name: Setup conda environment
              uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                python-version: 3.7
                activate-environment: signature-layout-test
                environment-file: tests/environment.yaml
            - run: snakemake -s tests/test.smk --cores 1
